# Generated by Django 3.2.3 on 2025-02-26 16:23

import builtins
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('dob', models.DateField(verbose_name=builtins.max)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('address', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(default=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='student-avatars/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
